<a href="https://colab.research.google.com/github/kei-kobayashi-3/test-of-hypothesis/blob/main/Lesson5_%E4%BB%AE%E8%AA%AC%E6%A4%9C%E5%AE%9A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cd /./

In [ ]:
ls -a

./     content/     etc/    lib64/  proc/  srv/                tmp/
../    datalab/     home/   media/  root/  swift/              tools/
bin/   dev/         lib/    mnt/    run/   sys/                usr/
boot/  .dockerenv*  lib32/  opt/    sbin/  tensorflow-1.15.2/  var/


In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/

/content/drive/MyDrive/Colab Notebooks


In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline

In [ ]:
data1=pd.read_csv('Lesson5-1.csv')

In [ ]:
data1

Length
0   56.873036
1   50.164731
2   50.415485
3   48.781094
4   54.596223
5   45.095384
6   57.234435
7   49.716379
8   52.957117
9   51.251889
10  56.386324
11  45.819578
12  51.032748
13  50.847837
14  55.401308
15  48.700326
16  51.482715
17  49.366425
18  52.126641
19  53.748446
20  48.698142
21  55.434171
22  54.704772
23  53.507483
24  54.702568
25  49.948816
26  51.631329
27  49.192692
28  51.196336
29  53.591066

In [ ]:
# 標本平均

In [ ]:
mu=np.mean(data1)
mu

Length    51.820183
dtype: float64

In [ ]:
#　自由度

In [ ]:
df=len(data1)-1
df

29

In [ ]:
# 標準誤差の計算

In [ ]:
sigma=np.std(data1,ddof=1)
sigma

Length    3.079095
dtype: float64

In [ ]:
se=sigma/np.sqrt(len(data1))
se

Length    0.562163
dtype: float64

この情報を元に「池の魚平均体長は50cmと等しいか」について調べてみましょう。
両側検定になりますね。有意水準は5％とします。帰無仮説・対立仮説は以下の通りです。

*  帰無仮説（H0）: 池の中の魚の平均体長は50cmである
*  対立仮説（H1）: 池の中の魚の平均体長は50cmとは異なる

In [ ]:
# t値の計算

In [ ]:
t_value=(mu-50)/se
t_value

Length    3.237819
dtype: float64

In [ ]:
# p値の計算  def cdf(x, *args, **kwds)Cumulative distribution function of the given RV.

In [ ]:
alpha=stats.t.cdf(np.abs(t_value),df=df) #上側部分
alpha

array([0.99849387])

In [ ]:
(1-alpha)*2  # alphaより大きい部分の確率　の上側下側その確率 p値 

array([0.00301227])

p値が0.05を下回っているので、”有意差あり”とみなすことができます。よって、「池の魚の平均体長は50cmと有意に異なる」と判断できます。

In [ ]:
# 以上の計算はstats.ttest_1samp関数を用いると下記のように実行できます t_value, p_value

In [ ]:
t=stats.ttest_1samp(data1,50)
t

Ttest_1sampResult(statistic=array([3.23781919]), pvalue=array([0.00301227]))

「池の魚の平均体長は50cmより大きい」かどうかを調べてみましょう。こちらも有意差5％とします。今度は片側検定を実行することになります。仮説は以下の通りです。

*  帰無仮説（H0）: 池の中の魚の平均体長は50cmである
*  対立仮説（H1）: 池の中の魚の平均体長は50cmより大きい


In [ ]:
# t値を求める

In [ ]:
t_value=((mu-50)/np.std(data1,ddof=1))*np.sqrt(len(data1))
t_value

Length    3.237819
dtype: float64

In [ ]:
# p値を求める

In [ ]:
alpha=stats.t.cdf(t_value,df=df)
alpha

array([0.99849387])

In [ ]:
1-alpha

array([0.00150613])

In [ ]:
stats.ttest_1samp(data1,50)

Ttest_1sampResult(statistic=array([3.23781919]), pvalue=array([0.00301227]))

In [ ]:
# こちらもp値が0.05を下回っているので”有意差あり”とみなすことができます。よって、「池の魚の平均体長は50cmより有意に大きい」と判断できます。

2変量データのt検定

今までは1つの池の中の魚の体長といった「1変量のデータ」について考えてきました。次は、「飼料Aで育った養殖魚と飼料Bで育った養殖魚の体長」「2歳魚と3歳魚の体長」といった2変数の間で平均値に差があるか否かについて考えてみましょう

In [ ]:
data2=pd.read_csv('Lesson5-2.csv')

In [ ]:
data2.head(3)

2-years-old  3-years-old
0    16.624345    14.600841
1    14.388244    14.984220
2    14.471828    14.606675

In [ ]:
data2['difference']=data2['3-years-old']-data2['2-years-old']

もし魚が年齢を重ねることが体長に何の影響も与えないのであれば、この差は0になるはずです。逆に言えば、差の平均値が0と異なれば、2歳魚と3歳魚で体長が異なると判断できるわけです。よって、対応のあるt検定では「差が0と異なるか」という1変数のt検定を行うことになります。

帰無仮説と対立仮説について確認しましょう。対応のあるt検定では下記の仮説を立てることになりますが、これは括弧書きのように解釈できるという意味です。

*  帰無仮説（H0）: 2歳魚と3歳魚で体長は変わらない（2歳魚と3歳魚の体長の差は0）
*  対立仮説（H1）: 2歳魚と3歳魚で体長は異なる（2歳魚と3歳魚の体長の差は0ではない）



In [ ]:
# t検定 　def ttest_1samp(a, popmean, axis=0, nan_policy='propagate')  popmean:帰無仮説の平均

In [ ]:
stats.ttest_1samp(data2['difference'],0)

Ttest_1sampResult(statistic=2.212896760339997, pvalue=0.03493196300425262)

In [ ]:
# p値が0.05を下回りましたので、「2歳魚と3歳魚の体長は有意に異なる」と判断できました。

対応のないt検定
対応のあるt検定では、それぞれの個体について2歳時点と3歳時点の2回計測を行った結果について解析しました。それでは、このデータが「2歳魚を集めたデータ」と「3歳魚を集めたデータ」ではあるものの同じ個体の2歳時と3歳時の体長を測定したものではないとするとどうなるでしょうか。今度は、「平均値の差」について注目する必要があります。

平均値の差に基づいてt値を計算する場合、少し計算式が複雑になります。2歳魚の体長をX、3歳魚の体長をYとすると下記のように計算できます。
*  $\hat\mu_x $ : Xの標本平均
*  $\hat\mu_y$ : Yの標本平均
*  $m$ : Xのサンプル数
*  $n$ : Yのサンプル数
*  $\hat\sigma_x^2$ : Xの不偏分散
*  $\hat\sigma_y^2$ : Yの不偏分散



\begin{eqnarray}
  t=\frac{\hat\mu_x-\hat\mu_y}{\sqrt{\frac{\hat\sigma_x^2}{m}+\frac{\hat\sigma_y^2}{n}}}  \\\\
  自由度:f=\frac{(\frac{\hat\sigma_x^2}{m}+\frac{\hat\sigma_y^2}{n})^2}{\frac{\frac{\hat\sigma_x^2}{m}}{m-1}+\frac{\frac{\hat\sigma_y^2}{n}}{n-1}}
\end{eqnarray}

In [ ]:
# 対応のないt検定はstats.ttest_ind関数を用いると簡単に計算できます  welch def ttest_ind(a, b, axis=0, equal_var=True, nan_policy='propagate')

In [ ]:
stats.ttest_ind(data2['2-years-old'],data2['3-years-old'],equal_var=False)

Ttest_indResult(statistic=-2.403807649264687, pvalue=0.01945646990570736)

In [ ]:
# p値が0.05を下回ったので「2歳魚と3歳魚の体長は有意に異なる」と判断できました

仮説検定における注意点
基本的な仮説検定の考え方と計算の仕方について学習してきました。ここで、仮説検定に対して誤った考え方をしてしまうのを防ぐために、下記の3点について確認しておきましょう。

*  ① p値が小さくても、「差が大きい」とは限らない
p値を求める前にt値を計算しました。そのt値が大きくなればp値も小さくなり、「有意差あり」と主張しやすくなりましたね。ですがこのt値というのは分子の「標本平均—比較対象」の差の他にサンプルサイズも影響しています。ですので、p値だけをみて「差の大きさ」を判断することはできません。

*  ② p値が0.05よりも大きくても「差がない」とは言えない
p値というのは「帰無仮説の元で検定統計量がその値となる確率」でした。「帰無仮説が間違っている確率」はp値という指標でコントロールできますが、「帰無仮説が正しい確率」はコントロールできません。よって、p値により「差がない」ということを証明することはできません。

*  ③「1-p値」は「対立仮説が正しい確率」ではない
こちらも上記と同様です。

